CREATE TABLE `interactions` (
  `interaction_id` int(11) NOT NULL AUTO_INCREMENT,
  `webmention_id` int(11) NOT NULL,
  `post_id` int(11) DEFAULT NULL,
  `page_id` int(11) DEFAULT NULL,
  `interaction_type` ENUM('reply','like','repost', 'mention', 'tag', 'tagged', 'rsvp') DEFAULT 'mention',
  `body` text DEFAULT NULL,
  `author_name` varchar(200) DEFAULT NULL,
  `author_url` varchar(300) DEFAULT NULL,
  `author_image` varchar(300) DEFAULT NULL,
  `source_name` varchar(45) DEFAULT NULL,
  `source_url` varchar(150) DEFAULT NULL,
  `timestamp` timestamp NULL DEFAULT NULL,
  `parse_timestamp` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `approved` tinyint(4) DEFAULT '0',
  `tag_category` varchar(100) DEFAULT NULL,
  `tag_person_name` varchar(200) DEFAULT NULL,
  `tag_person_url` varchar(300) DEFAULT NULL,
  `tag_shape` varchar(45) DEFAULT NULL,
  `tag_coords` varchar(100) DEFAULT NULL,
  `tag_of` varchar(150) DEFAULT NULL,
  `rsvp_response` ENUM('attending', 'not attending', 'maybe attending', 'remote attending') DEFAULT 'maybe attending',
  `deleted` tinyint(1) DEFAULT 0,
  PRIMARY KEY (`interaction_id`)
) ENGINE=InnoDB AUTO_INCREMENT=62 DEFAULT CHARSET=utf8;
